# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI and CD reusable caller

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  call-maven-ci-cd-reusable-workflow:
    uses: harman-automotive/vehicle-profile/.github/workflows/maven-ci-cd-reusable.yml@main
    with :
      api-service-name: 'ro-api'
      sp-service-name: 'ro-sp'
    
    secrets: inherit
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
